Предлагаю вариант интерфейса для итератора
ThinkingFrog/IVector pull request #20
Opened 2021-03-17 15:34 UTC by AlexeyBurkov

closes #19

2021-03-17 16:34 UTC, ThinkingFrog requested changes

2021-03-17 16:34 UTC, ThinkingFrog commented on include/ISet.h
> +		virtual IVector const * const getPtr() = 0;
Очевидно не хватает метода для итерации, типа toNext() и тогда ещё логично toPrev()

2021-03-17 16:34 UTC, ThinkingFrog commented on include/ISet.h
> +		static bool equal(const IIterator *op1, const IIterator *op2);
Не уверен, что когда-нибудь будет нужно сравнить именно итераторы, а не их значения из геттеров

2021-03-17 16:34 UTC, ThinkingFrog commented on include/ISet.h
> +		virtual IVector const * const getPtr() = 0;
В чём отличие, если и там, и там возвращается указатель?

2021-03-17 16:34 UTC, ThinkingFrog commented on include/ISet.h
> +	class IIterator {
Может всё-таки сделать внешним классом?

2021-03-17 16:34 UTC, ThinkingFrog commented on include/ISet.h
> +		virtual IIterator * previous(size_t indexDec = 1) override = 0;
Что здесь оверрайдится, если нет базового класса?

2021-03-17 16:34 UTC, ThinkingFrog commented on include/ISet.h
> +		virtual IIterator * previous(size_t indexDec = 1) override = 0;
Если я правильно понимаю их назначение, эти два метода константные

2021-03-17 16:34 UTC, ThinkingFrog commented on include/ISet.h
> +	IIterator *getEnd();
Думаю, нужны ещё фабрики для константных итераторов

2021-03-17 16:34 UTC, ThinkingFrog commented on include/ISet.h
> +		virtual IVector const * const getPtr() = 0;
По-хорошему надо сделать один из методов константным, чтобы константный итератор мог возвращать только копию

2021-03-17 16:46 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual IVector const * const getPtr() = 0;
Я подразумевал, что `next` и `previous` это они и есть. Возвращает указатель на текущий итератор, чтобы можно было писать конструкции типо `next()->getValue()`

2021-03-17 16:47 UTC, AlexeyBurkov commented on include/ISet.h
> +		static bool equal(const IIterator *op1, const IIterator *op2);
Насколько я помню у нас геттер делает deepcopy, а делать ради проверки 2 копии не хорошо.

2021-03-17 16:49 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual IVector const * const getPtr() = 0;
`getValue` делает deepcopy, а `getPtr` нужен для того, чтобы можно было сравнивать итераторы по сути (можно сделать приватным)

2021-03-17 16:50 UTC, AlexeyBurkov commented on include/ISet.h
> +	class IIterator {
Можно, особой разницы не вижу.

2021-03-17 16:51 UTC, AlexeyBurkov commented on include/ISet.h
> +	IIterator *getEnd();
По сути у нас и есть константный итератор, так как мы не можем изменять вектора, не сделав их копию.

2021-03-17 16:52 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual IIterator * previous(size_t indexDec = 1) override = 0;
Очепятка

2021-03-17 16:57 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual IVector const * const getPtr() = 0;
Я понял, нужно комменты написать по методам.

2021-03-17 19:49 UTC, ThinkingFrog commented on include/ISet.h
> +		virtual IVector const * const getPtr() = 0;
Тогда next скорее всего не должен ничего возвращать. Мне кажется, лучше всё-таки сделать две группы методов: которые возвращают соседние итераторы без перемещений, и которые перемещают итераторы на соседние без возвращения

2021-03-17 20:36 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual IVector const * const getPtr() = 0;
Добавил.

2021-03-17 20:37 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual IVector const * const getPtr() = 0;
Сделал приватным.

2021-03-17 20:37 UTC, AlexeyBurkov commented on include/ISet.h
> +	class IIterator {
Сделал внешним классом.

2021-03-18 06:45 UTC, ThinkingFrog commented on include/ISet.h
> +public:
В самом итераторе нет никакой фабрики или открытых конструкторов. Во-первых мы просто не сможем создать итератор из методов множества, во-вторых хотелось бы иметь возможность создать итератор на основе множества. Нужен метод вроде ISetIterator* CreateIterator(ISet* set)

2021-03-18 06:45 UTC, ThinkingFrog commented on include/ISet.h
> +	virtual RC getValue(IVector const* val) const = 0;
В прошлом обсуждении ты меня видимо неправильно понял. Я за то, чтобы была возможность извне получить значение вектора и по копии, и по указателю. В прошлой версии просто не было разницы между двумя методами

2021-03-18 08:51 UTC, AlexeyBurkov commented on include/ISet.h
> +	virtual RC getValue(IVector const* val) const = 0;
Я не уверен, что такая возможность нужна, в силу того, что вектора могут релоцироваться в процессе реаллокации. У нас нет такого метода в ISet - не должно быть и здесь.

2021-03-18 08:57 UTC, AlexeyBurkov commented on include/ISet.h
> +public:
Я полагаю реализация итератора будет находится в той же .dll, что и реализация ISet. Если вспомнить тот же вектор, то у нас тоже нет никаких объявленных конструкторов, с помощью которых можно было бы собрать экземпляр: такой конструктор есть у реализации, и для возможности создать вектор он является публичным внутри библиотеки. Аналогично и тут: у реализации итератора будет публичный конструктор или публичная фабрика, которая будет использована при реализации соответствующего getIterator метода ISet.

Нужна ли фабрика для самого итератора, учитывая, что она будет идентична методам ISet?

2021-03-18 09:02 UTC, AlexeyBurkov commented on include/ISet.h
> +	virtual RC getValue(IVector const* val) const = 0;
Ну или нужно добавить такой метод и написать капсом о возможных ивалидациях таких shallow копий в процессе insert'ов.

2021-03-19 09:26 UTC, MekhailS commented
Вопрос касательно `previous()` каким образом предлагается реализовывать эту операцию? Сейчас у нас вектора фактически хранятся в односвязном списке, на что я указывал в #22. Таким образом, сложность `previous()` оценивается как O(n). Насколько разумно вообще это вводить?

2021-03-19 09:51 UTC, MekhailS commented on include/ISet.h
> +	virtual RC getValue(IVector const* val) const = 0;
На мой взгляд у паблик итератора действительно не должно быть возможности получать вектор как shallow copy.

2021-03-19 11:20 UTC, AlexeyBurkov commented
На счёт #22 я думаю так: можно изменить хранимый блок с вектором: добавить рядом с вектором 2 указателя (один на предыдущий вектор, другой на следующий). Первое что пришло в голову. Так как в целом исповедуем подход "хер с ней с памятью, лишь бы до конца работы программы дожить", думаю не очень плохое решение.

2021-03-19 11:31 UTC, AlexeyBurkov commented
А вообще, если в итераторе хранить просто указатель на вектор (т.е. снова эта shallow copy), то такой итератор мягко говоря не слишком надёжный. И если реализовывать надёжный вариант, то придётся иногда (в случае трудного `insert'а`) выполнять линейный поиск по `ISet`, чтобы найти актуальный указатель на вектор (обновить shallow copy). Т.е. линейного поиска не избежать всё равно.

2021-03-19 11:33 UTC, MekhailS commented
> На счёт #22 я думаю так: можно изменить хранимый блок с вектором: добавить рядом с вектором указатель или `size_t` (на предыдущий вектор или размер предыдущего вектора). Первое что пришло в голову. Так как в целом исповедуем подход "хер с ней с памятью, лишь бы до конца работы программы дожить", думаю не очень плохое решение.

На мой взгляд это решение  с дополнительным размещением размера вектора в его конце скатывает нас в ужасное, страшное, неудобное скатывание в низкоуровневое программирование, никому, пожалуй, не понравится работать с памятью вручную. Проще будет тупо убрать `previous`.

2021-03-19 11:35 UTC, MekhailS commented
> А вообще, если в итераторе хранить просто указатель на вектор (т.е. снова эта shallow copy), то такой итератор мягко говоря не слишком надёжный. И если реализовывать надёжный вариант, то придётся иногда (в случае трудного `insert'а`) выполнять линейный поиск по `ISet`, чтобы найти актуальный указатель на вектор (обновить shallow copy). Т.е. линейного поиска не избежать всё равно.

Не совсем понимаю о чем ты,
Итератор же по контракту становится невалидным после удаления/добавления элементов в вектор

2021-03-19 14:31 UTC, AlexeyBurkov commented
> > А вообще, если в итераторе хранить просто указатель на вектор (т.е. снова эта shallow copy), то такой итератор мягко говоря не слишком надёжный. И если реализовывать надёжный вариант, то придётся иногда (в случае трудного `insert'а`) выполнять линейный поиск по `ISet`, чтобы найти актуальный указатель на вектор (обновить shallow copy). Т.е. линейного поиска не избежать всё равно.
> 
> Не совсем понимаю о чем ты,
> Итератор же по контракту становится невалидным после удаления/добавления элементов в вектор

Не обязательно становится невалидным, кто ему мешает оставаться валидным? Это уже как договоримся.

2021-03-19 14:33 UTC, AlexeyBurkov commented
> > На счёт #22 я думаю так: можно изменить хранимый блок с вектором: добавить рядом с вектором указатель или `size_t` (на предыдущий вектор или размер предыдущего вектора). Первое что пришло в голову. Так как в целом исповедуем подход "хер с ней с памятью, лишь бы до конца работы программы дожить", думаю не очень плохое решение.
> 
> На мой взгляд это решение с дополнительным размещением размера вектора в его конце скатывает нас в ужасное, страшное, неудобное скатывание в низкоуровневое программирование, никому, пожалуй, не понравится работать с памятью вручную. Проще будет тупо убрать `previous`.

Мы и так изображаем из себя низкоуровневых погромистов с этими хитрыми махинациями с памятью. К тому же это частное решение, может кто-то напишет решение в стиле ооп, тоже можно.

2021-03-19 19:00 UTC, ThinkingFrog commented on include/ISet.h
> +public:
Хорошо, а как вообще тогда итератор создавать? Вот у меня есть ISetIterator*, как я в него положу свой объект?

2021-03-19 19:02 UTC, ThinkingFrog commented on include/ISet.h
> +	virtual RC getValue(IVector const* val) const = 0;
А если мне надо будет поменять что-то в сете? Вот я хочу проитерироваться по всем векторам в множестве и применить к каждому scale(), как мне это сделать?

2021-03-20 12:46 UTC, AlexeyBurkov commented on include/ISet.h
> +public:
`pIt = set_obj.getIterator()`, не?

2021-03-20 19:54 UTC, ThinkingFrog commented on include/ISet.h
> +public:
Так а getIterator как итератор создаст?

2021-03-20 20:45 UTC, AlexeyBurkov commented on include/ISet.h
> +public:
Реализация паблик конструктор будет иметь, ровно как у вектора. Так или иначе фабрика будет в другом классе, в котором ни намёка на конструктор.

2021-03-23 08:44 UTC, ThinkingFrog commented on include/ISet.h
> +		virtual IVector const * const getPtr() const = 0;
Если хотим, чтобы этот метод можно было перегрузить, то его нужно сделать protected

2021-03-23 08:44 UTC, ThinkingFrog commented on include/ISet.h
> +	};
Я всё ещё не могу понять, как создавать новый объект итератора, если нет ни одного публичного конструктора или фабрики. Можно мне прям кусок кода показать, который создаст этот объект?

2021-03-23 14:46 UTC, AlexeyBurkov commented on include/ISet.h
> +	};
@ThinkingFrog, полагаю так:
```
//isetimpl.cpp
class IteratorImpl : public ISet::IIterator {
public:
    IteratorImpl(SomeType some_param);
...
};

class ISetImpl : public ISet {
public:
...
    IIterator *getIterator() {
        return new IteratorImpl(some_arg);
    }
...
};
```

2021-03-23 14:49 UTC, AlexeyBurkov commented on include/ISet.h
> +	};
Полоностью аналогично тому как у нас происходит в векторе: реализация вектора заранее неизвестна, но в другом классе `IVector` объявлен метод, который создаёт экземпляр класса реализации. Тут то же самое, только фабрика находится не в интерфейсе итератора, а в интерфейсе `ISet`.

2021-03-23 15:54 UTC, ThinkingFrog commented on include/ISet.h
> +	};
Вообще это странно и контринтуитивно, что за создание объекта одного класса отвечает метод другого класса. К тому же Иванков даст по рукам за то, что мы можем вызывать из внешнего кода что-то типа ISetImpl::IteratorImpl(some_arg) и получить итератор напрямую из конструктора. Я за то, чтобы сделать в итераторе фабрику, как во всех остальных классах, но при этом и оставить фабрику во множестве, которая будет вызывать фабрику итератора с разными аргументами. В крайнем случае сделать фабрику протектед, чтобы её можно было вызывать только из множества, а не из внешнего мира

2021-03-23 18:10 UTC, AlexeyBurkov commented on include/ISet.h
> +	};
Из внешнего мира невозможно вызвать этот конструктор, потому что никто не знает о том, что он существует. Почему тогда не напрягает `IVector`, там тоже за создание объекта отвечает другой класс? Более того, мы не сможем создать итератор просто так. Итератор привязан к реализации `ISet`, т.е. невозможно создать итератор зная интерфейс или не зная ничего.

2021-03-23 20:24 UTC, MekhailS requested changes

2021-03-23 20:24 UTC, MekhailS commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
Предлагаю убрать previous из интерфейса итератора за его ненадобностью и сложностью в имплементации ISet'а поддерживающего итерацию по элементам назад.
(Иванков подтвердил, что итерирование назад можно не поддерживать)

2021-03-23 21:16 UTC, ThinkingFrog commented on include/ISet.h
> +	};
В любом случае это не интуитивно. Нужно хотя бы оставить комментарий в коде об этом

2021-03-24 09:13 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
Насколько я помню, он сказал, что храним не вектора, а сами значения. В результате операции `next` и `previous` будут легко имплементированны. Я считаю, что нам обе операции понадобятся.

2021-03-24 09:39 UTC, ThinkingFrog commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
Из-за того, что мы руками менеджерим обалсть памяти под вектора в множестве, действительно будут проблемы с итерированием назад. Память под вектора будет похожа на кучу, храниться в односвязном списке. В односвязном списке довольно сложно ходить назад. Иванков действительно подтвердил, что назад можно не ходить

2021-03-24 09:44 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
Нет ну раз вам не хочется то пожалуйста, мне пофиг. Но на лекции лично слышал как он сказал про то, что храним элементы только. Если храним только элементы, то сделать шаг назад не трудно. Кроме того, в компакте всё равно придётся реализовывать итератор во всех направлениях, так что не понимаю огрничение этого итертора.

2021-03-24 10:48 UTC, MekhailS commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
Да, он предложил эту реализацию, но тогда каждый раз для обращения к элементу Set'а (даже внутри самого Set'а) придется конструировать новый объект вектора, что неэффективно и убого

2021-03-24 12:25 UTC, ThinkingFrog commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
Предлагаю оставить, если что, можно реализовать метод пустым. Может быть где-то стоит подписать, что перегрузка этого метода не обязательна, либо вовсе сделать его не чисто виртуальным

2021-03-24 17:26 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
> Да, он предложил эту реализацию, но тогда каждый раз для обращения к элементу Set'а (даже внутри самого Set'а) придется конструировать новый объект вектора, что неэффективно и убого

В чём неэффективность? В любом случае выполняется выделение и копирование объёма памяти.

2021-03-25 19:30 UTC, MekhailS commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
> Предлагаю оставить, если что, можно реализовать метод пустым. Может быть где-то стоит подписать, что перегрузка этого метода не обязательна, либо вовсе сделать его не чисто виртуальным

Зачем оставлять и разрешать реализовывать пустую реализацию? Выпилить проще

2021-03-25 19:35 UTC, MekhailS commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
> > Да, он предложил эту реализацию, но тогда каждый раз для обращения к элементу Set'а (даже внутри самого Set'а) придется конструировать новый объект вектора, что неэффективно и убого
> 
> В чём неэффективность? В любом случае выполняется выделение и копирование объёма памяти.

Как минимум, в `findFirst` и `remove` при поиске элемента будем вечно конструировать вектора, + фактически, принимая данную реализацию, мы плюем на полиморфизм и на разные имплементации векторов, т.к. по итогу в Set'е с векторами ассоциируем массивы из double'ов.

2021-03-25 20:41 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
> > > Да, он предложил эту реализацию, но тогда каждый раз для обращения к элементу Set'а (даже внутри самого Set'а) придется конструировать новый объект вектора, что неэффективно и убого
> > 
> > 
> > В чём неэффективность? В любом случае выполняется выделение и копирование объёма памяти.
> 
> Как минимум, в `findFirst`, `insert` и `remove` при поиске элемента будем вечно конструировать вектора (а если подумать о том, сколько раз будут вызываться эти методы при конструировании пересечений/объединений и пр. , страшно становится), + фактически, принимая данную реализацию, мы плюем на полиморфизм и на разные имплементации векторов, т.к. по итогу в Set'е с векторами ассоциируем массивы из double'ов.

1) почему `remove` будет требовать кострукции вектора?
2) если хранить вектора целиком, возвращать придётся копию всё равно: всё равно нужно выделить память, всё равно нужно сделать копию, в чём выгода?
3) то, что мы делаем это не полиморфизм, а пимпл: у нас нет иерархии классов, нет никакой информации о том, что там за реализация. Но при этом ISet может работать с любыми векторами (с любой реализацией), потому что работает с интерфейсом. Нет никакой проблемы, как хранить вектора каждый решает самостоятельно.

2021-03-25 21:45 UTC, MekhailS commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
> > > > Да, он предложил эту реализацию, но тогда каждый раз для обращения к элементу Set'а (даже внутри самого Set'а) придется конструировать новый объект вектора, что неэффективно и убого
> > > 
> > > 
> > > В чём неэффективность? В любом случае выполняется выделение и копирование объёма памяти.
> > 
> > 
> > Как минимум, в `findFirst`, `insert` и `remove` при поиске элемента будем вечно конструировать вектора (а если подумать о том, сколько раз будут вызываться эти методы при конструировании пересечений/объединений и пр. , страшно становится), + фактически, принимая данную реализацию, мы плюем на полиморфизм и на разные имплементации векторов, т.к. по итогу в Set'е с векторами ассоциируем массивы из double'ов.
> 
> 1. почему `remove` будет требовать кострукции вектора?
> 2. если хранить вектора целиком, возвращать придётся копию всё равно: всё равно нужно выделить память, всё равно нужно сделать копию, в чём выгода?
> 3. то, что мы делаем это не полиморфизм, а пимпл: у нас нет иерархии классов, нет никакой информации о том, что там за реализация. Но при этом ISet может работать с любыми векторами (с любой реализацией), потому что работает с интерфейсом. Нет никакой проблемы, как хранить вектора каждый решает самостоятельно.

1. Для того, чтобы из Set'а удалить вектора, похожие на данный, необходимо проитерироваться по всем векторам Set'а.
2. Для того, чтобы **проитерироваться** по всем **векторам** ISet'а (внутри предложенной имплементации ISet'а), нужно для каждого массива double вызвать `createVector` от этого массива, для того, чтобы получить **вектор**. Таким образом, если у нас ISet состоит из n "векторов", для того, чтобы проитерироваться по каждому из них (внутри имплементации!) нужно n раз вызвать `createVector`
3. Мы, видимо, по разному понимаем полиморфизм. Имплементация интерфейса, и дальнейшее общение с конкретной реализацией через интерфейс это уже есть полиморфизм. Не понимаю, где ты тут разглядел пимпл: мы общаемся с разными реализациями через единый интерфейс. А не с конкретной реализацией через "интерфейсный" класс. То, что мы делаем, это скорей Bridge (а бриджа без полиморфизма и не может быть).

К вопросу, почему реализация с хранением в Set'е векторов в виде массивов double не полиморфизм: потому что таким образом мы, фактически, кастим абстрактные имлементации IVector'а к конкретной имплементации из `createVector` (достали данные из абстрактного вектора - сохранили - создали через `createVector` вектор с этими данными).

P.S. Касательно того, что каждый волен выбирать реализацию вектора сам: это не так. Иванкову непросто будет сдать нормальную stl'ную имплементацию, ему принципиально хочется чтобы мы руками с памятью работали ради "оптимизации". Эта "оптимизация" реализации нас загнала в ситуацию, что не получается адекватно реализовать ISet, и на данный момент общепринятая реализация приводит к O(n) `previous`, альтернатива — хранение вектора в виде массива double, в результате — аллоцирование нового вектора при обращении к оному, что тоже не оптимально. Ещё один вариант — хранение размера вектора в конце, в вопросе оптимальности решение хорошее, но давайте ради общего блага этот вариант не упоминать. 
Удаление `previous` — это оптимизация интерфейса под реализацию (самую простую, предложенную на том же занятии, на котором сам ISet был анонсирован).

2021-03-25 22:23 UTC, AlexeyBurkov commented on include/ISet.h
> +		virtual RC previous(size_t indexDec = 1) = 0;
@MekhailS
1), 2) понял, но тем не менее можно работать просто с double, с учётом того, что операции вычисления нормы разности (которая нужна для поиска) придётся для `ISet` запилить повторно (мы можем получить const double * искомого вектора и векторов внутри `ISet` без построения копии, и просто выполнить сравнение по определённой норме).

Но на это можно забить в контексте лабы, в контексте общего блага. На счёт общего блага согласен, но тем не менее не обязательно строить копии, чтобы проитерироваться.

По поводу 3). Ещё раз объясняю то, что я сказал: у нас никакого подиморфизма нет в том смысле, что у нас 1 единственный класс: интерфейс. Всё остальное - никому не известные кишики реализации, которые сидят внутри и не отсвечивают. Никто не знает о том, что там какие-то разные классы, наследуемые от общего интерфейса. Этой информации тупо нет, извне мы работает только с IVector.

Хорошо, давайте удалим `previous`, для общего блага.

2021-04-02 14:30 UTC, ThinkingFrog approved these changes

2021-04-02 14:30 UTC, ThinkingFrog reviewed
@AlexeyBurkov @MekhailS Просмотрите быстро ещё раз и давайте наконец заливать

2021-04-02 17:59 UTC, AlexeyBurkov commented
Меня всё устраивает, разве что не понятно `previous` возвращаем или нет.

2021-04-09 11:38 UTC, AlexeyBurkov commented
Я считаю добавлять больше нечего, думаю можно мержить.

2021-04-09 13:15 UTC, ThinkingFrog commented on include/ISet.h
> +        virtual size_t getIndex() const = 0;
Не очень понимаю, почему этот метод protected, а не public

2021-04-09 14:23 UTC, ThinkingFrog commented on include/ISet.h
> +    virtual RC insert(IVector const * const& val, IVector::NORM n, double tol) = 0;
Зачем в insert норма и tol?

2021-04-09 14:23 UTC, ThinkingFrog commented on include/ISet.h
> +    static ISet* symSub(ISet const * const& op1, ISet const * const& op2, IVector::NORM n, double tol);
Надо где-то описать, для чего нужен этот метод

2021-04-09 15:50 UTC, AlexeyBurkov commented on include/ISet.h
> +        virtual size_t getIndex() const = 0;
Потому что они относится к внутреннему устройству вектора, пользователь с этим индексом ничего не сделает, это тот самы присловутый хэш.

2021-04-09 15:52 UTC, AlexeyBurkov commented on include/ISet.h
> +    virtual RC insert(IVector const * const& val, IVector::NORM n, double tol) = 0;
Так изначально ввели. По этим параметрам мы проверим, есть ли внутри ISet уже вектор с точностью до tol (т.е. если расстояние между 2мя точками по этой метрике будет меньше tol, то считай что вектор уже есть).

2021-04-09 15:55 UTC, AlexeyBurkov commented on include/ISet.h
> +    static ISet* symSub(ISet const * const& op1, ISet const * const& op2, IVector::NORM n, double tol);
Ок, тогда напишу описание подробнее.

2021-04-09 19:54 UTC, ThinkingFrog approved these changes

2021-04-10 16:58 UTC, merged