Описание итерфейсов
ThinkingFrog/IVector pull request #34
Opened 2021-04-02 09:18 UTC by AlexeyBurkov

Считаю необходимым добавить описание интерфейсов, чтобы потом не было вопросв от коллег, которые скипнули все обсуждения.
Пока добавил то, что считаю нужным.

2021-04-03 13:52 UTC, ThinkingFrog approved these changes

2021-04-08 08:40 UTC, ThinkingFrog requested changes
Нужно добавить про итератор и мультииндекс

2021-04-09 08:55 UTC, AlexeyBurkov commented
Про итератор `ISet` нужно написать ту сложную схему, по которой он должен работать?

2021-04-09 09:23 UTC, ThinkingFrog commented
> Про итератор `ISet` нужно написать ту сложную схему, по которой он должен работать?

Да

2021-04-09 15:59 UTC, AlexeyBurkov commented
Для себя помечу. Нужно добавить про размерность ISet и подробнее написать про... всё.

2021-04-14 10:19 UTC, ThinkingFrog approved these changes
Считаю, что нужно заливать, как есть сейчас, а потом уже допиливать если что

2021-04-14 12:45 UTC, AlexeyBurkov commented
ISet доделаю и можно вливать, остался итератор

2021-04-14 13:29 UTC, AlexeyBurkov commented
Я пока не написал про интерфейс контрольного блока, так как его пока нет. Если ничего критичного нет, можно мерджить. Я дальше тут же продолжу делать.

2021-04-14 17:11 UTC, ThinkingFrog approved these changes

2021-04-14 17:12 UTC, merged