Интерфейс целевой функции
ThinkingFrog/IVector pull request #39
Opened 2021-04-03 20:44 UTC by AlexeyBurkov

2021-04-09 15:05 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +    virtual IVector *evalGradientByParams(IVector const *params) const = 0;
В чём отличие args от params?

2021-04-09 15:49 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +    virtual IVector *evalGradientByParams(IVector const *params) const = 0;
Параметры и аргументы функции. Например `ax^2+by+c`, a, b, c - параметры, x, y - аргументы. Я сам смысл разделения не понял, но вроде для какого-то метода надо. Так вводил иаа.

2021-04-09 19:55 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +    virtual IVector *evalGradientByParams(IVector const *params) const = 0;
Нужно будет где-то это тоже отразить

2021-04-10 17:00 UTC, ThinkingFrog approved these changes

2021-04-10 18:30 UTC, AlexeyBurkov commented
Драфт потому что не прикасались ещё к разработке реализации?

2021-04-10 20:06 UTC, ThinkingFrog commented
> Драфт потому что не прикасались ещё к разработке реализации?

Нет, мне нужно самому ещё посмотреть и подправить. Пометил для себя

2021-04-10 20:06 UTC, ThinkingFrog commented
> Драфт потому что не прикасались ещё к разработке реализации?

Нет, мне нужно самому ещё посмотреть и подправить. Пометил для себя

2021-04-13 15:57 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
Здесь const слева от указателя намеренно или случайно?

2021-04-13 16:03 UTC, ThinkingFrog requested changes

2021-04-13 16:03 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +
Не хватает виртуального деструктора. Или будем считать, что здесь он в явном виде не нужен?

2021-04-13 16:03 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +    virtual IVector *evalGradientByParams(IVector const *params) const = 0;
Не может ли понадобиться отсюда RC возвращать?

2021-04-13 16:03 UTC, ThinkingFrog commented on include/IProblem.h
> +
Не может ли понадобиться возвращать отсюда RC?

2021-04-13 16:03 UTC, ThinkingFrog commented on include/IProblem.h
> +    virtual bool isValidArgs(IVector const * const &args) const = 0;
Каким образом предполагаются эти проверки?

2021-04-13 16:03 UTC, ThinkingFrog commented on include/IProblem.h
> +    virtual RC setArgs(IVector const * const &args) = 0;
Не стоит ли сделать параметры неизменяемыми, а аргументы задаваемыми только при вычислении? Мне вообще кажется логичной схема, когда параметры задаются только в конструкторе и больше никогда не могут изменяться, а аргументы задаются только для одного вычисления и никогда нигде не сохраняются

2021-04-13 16:06 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
Намеренно, мы передаём конкретную точку и конкретный мульти-индекс частной производной и должны получить число - значение частной производной. Или что-то не так?

2021-04-13 16:07 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +
Виртуальные методы все должны перейти от предка. Можно явно прописать конечно.

2021-04-13 16:10 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +    virtual IVector *evalGradientByParams(IVector const *params) const = 0;
Может. Изначально ввели так, но думаю не существенно как оно будет в итоге.

2021-04-13 16:13 UTC, AlexeyBurkov commented on include/IProblem.h
> +    virtual RC setArgs(IVector const * const &args) = 0;
Вроде для какого-то метода нужно иметь возможность вычислять функцию при разных параметрах.

Схему с фиксированием аргумента или параметра, а зетем вычислением значения по произвольному другому объекту (параметру или аргументу соответственно) придумал не я, но так вроде договорились.

2021-04-13 16:14 UTC, AlexeyBurkov commented on include/IProblem.h
> +    virtual bool isValidArgs(IVector const * const &args) const = 0;
Хороший вопрос, выглядит так, как будто в компакте не хватает соответствующего метода.

2021-04-14 10:21 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
Не понимаю, почему нельзя передавать не константные объекты и почему сам указатель не сделать константным

2021-04-14 10:24 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +
Я бы прописал в явном виде

2021-04-14 10:24 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +    virtual IVector *evalGradientByParams(IVector const *params) const = 0;
Надо тогда переделать, чтобы вектор передавался как аргумент, а возвращаемым значением был бы RC

2021-04-14 10:26 UTC, ThinkingFrog commented on include/IProblem.h
> +    virtual RC setArgs(IVector const * const &args) = 0;
Сейчас задача задаётся только с помощью параметров и аргументов, это единственное различие между всеми объектами. Поэтому мне кажется, что логично было бы сделать задачи с разными параметрами разными задачами. Но наверное это лучше обсудить с Иванковым

2021-04-14 12:47 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
А зачем так вектор не константный?

2021-04-14 13:06 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
А зачем константный? Зачем создавать ограничения, в которых нет смысла?

2021-04-14 13:16 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
Чтобы внутри этого метода нельзя было изменить значения элементов переданного вектора аргументов или параметров.

2021-04-14 13:42 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +
А это должно быть в виде:
```
void foo() override = 0;
```
Типо так?

2021-04-14 13:53 UTC, AlexeyBurkov commented on include/IProblem.h
> +
Пока что здесь логика как у скалярного произведения.

2021-04-15 09:14 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +
Нет, так же, как и обычно

2021-04-15 09:17 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
У нас и до этого были методы, в которых такие ограничения были бы логичны, но мы их не ставили

2021-04-15 09:26 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
Вроде везде ставили, например какие?

2021-04-22 18:54 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
Здесь ещё вопросы есть?

2021-04-22 18:55 UTC, AlexeyBurkov commented on include/IDiffProblem.h
> +
Компиляторы советуют при наследовании виртуальных методов писать `override`, а не `virtual`.

2021-04-22 18:55 UTC, AlexeyBurkov commented on include/IProblem.h
> +    virtual bool isValidArgs(IVector const * const &args) const = 0;
Метод в компакт добавлен, имплементация будет тривиальная.

2021-04-22 18:57 UTC, AlexeyBurkov commented on include/IProblem.h
> +    virtual RC setArgs(IVector const * const &args) = 0;
Посыл изначальный иаа таков: задача определяется двумя компактами.

2021-04-22 21:25 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +    virtual double evalDerivativeByParams(IVector const *params, IMultiIndex const *index) const = 0;
Да вроде ладно, если что, потом поправим

2021-04-22 21:26 UTC, ThinkingFrog commented on include/IDiffProblem.h
> +
Пусть тогда override будет, но я не вижу особо разницы

2021-04-22 21:36 UTC, ThinkingFrog approved these changes

2021-04-22 21:36 UTC, merged